# Generated by Django 4.2 on 2024-10-22 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={"verbose_name": "Привычка", "verbose_name_plural": "привычки"},
        ),
    ]
